<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vincent Pancini">
<meta name="dcterms.date" content="2026-04-20">

<title>Agencies - County</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="01_agency_geo_county_files/libs/clipboard/clipboard.min.js"></script>
<script src="01_agency_geo_county_files/libs/quarto-html/quarto.js"></script>
<script src="01_agency_geo_county_files/libs/quarto-html/popper.min.js"></script>
<script src="01_agency_geo_county_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="01_agency_geo_county_files/libs/quarto-html/anchor.min.js"></script>
<link href="01_agency_geo_county_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01_agency_geo_county_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="01_agency_geo_county_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="01_agency_geo_county_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="01_agency_geo_county_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Agencies - County</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Vincent Pancini </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<style>
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');
</style>
<p><link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidylog)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(urbnthemes)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set_urbn_defaults</span>(<span class="at">style =</span> <span class="st">"print"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This file is a prerequisite file to the following files:</p>
<ul>
<li><code>reported-crime-county-all.qmd</code> which creates the county-level metric for reported property crimes per 100,000 people and reported violent crimes per 100,000 people</li>
<li><code>juvenile-arrests-county-all.qmd</code> which creates the county-level metric for juvenile arrests per 100,000 juveniles</li>
</ul>
<p>You must run this file before either of the above files to create either metric at the county-level.</p>
<p>This file pulls in a universe of law enforcement agencies that have reported criminal activity and arrests in 2021-2024. It then joins on county FIPS codes to those agencies. For agencies that serve more than one county, this program assigns a weight to that agency to determine the percentage of activity that should be associated with each county served by that agency. Next, it pulls in population and demographic information from the American Community Survey (ACS). Lastly, it creates several files that are used in the creation of each metric.</p>
<p>The rest of this file is organized as follows:</p>
<ol type="1">
<li>Background and NIBRS Batch Header File download</li>
<li>Load and clean NIBRS Batch Header File</li>
<li>Join county FIPS codes onto NIBRS agencies that are missing county using Law Enforcement Agency Identifiers Crosswalk</li>
<li>Construct county-level population and demographics using ACS</li>
<li>Join Batch Header File onto ACS county demographics by county</li>
<li>Create county-agency weights</li>
<li>Write out data</li>
</ol>
<p>All data used in this file and to create the two safety metrics are available on Box <a href="https://urbanorg.box.com/s/poqnegsa6i74phcdr1eap7tacpe4x1gf">here</a>. Data stored on Box are only available to Urban Institute researchers.</p>
<p>This file assumes that you have cloned the GitHub repository for this project to your local computer. You can find the project repository <a href="https://github.com/UI-Research/mobility-from-poverty">here</a> and learn how to clone a repository <a href="https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository">here</a>.</p>
<section id="background-and-nibrs-batch-header-file-download" class="level2">
<h2 class="anchored" data-anchor-id="background-and-nibrs-batch-header-file-download">1. Background and NIBRS Batch Header File download</h2>
<p>This program and the safety metrics rely on National Incident-based Reporting System (NIBRS) data. NIBRS is an annual data collection that compiles information on criminal incidents and arrests reported by participating law enforcement agencies. It is a part of the Uniform Crime Reporting Program (UCR) which is administered by the Federal Bureau of Investigation (FBI).</p>
<p>NIBRS data as constructed and formatted by the FBI are stored in a single file. These data are organized by various segment levels (record types). Working with the NIBRS data in its single-file format is difficult. To facilitate use of NIBRS data, criminologist <a href="https://www.jacobdkaplan.com/">Jacob Kaplan</a> has cleaned and processed the data. We use these data which are available on <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CIQIVF&amp;version=1.0">Harvard Dataverse</a> and <a href="https://www.openicpsr.org/openicpsr/project/118281">ICPSR</a>. As of April 2026, the 2024 data was not yet on Harvard Dataverse, so all years (2021-2024) were downloaded from <a href="https://www.openicpsr.org/openicpsr/project/118281">Jacob Kaplan’s ICPSR repository</a> (V11, released August 2025).</p>
<p>The segment of NIBRS data this file is concerned with is called the Batch Header File (also called the Batch Header Segment). Prior to the 2013 data, the Batch Header information was released as three segments. Due to the NIBRS data rapidly growing in size, the FBI released a single file instead. The Batch Header File identifies individual police agencies by originating agency identifier (ORI). An individual police agency (ORI) will appear in the batch header segment once. It also includes variables for each county served by each agency, which is what we are particularly interested in. The data used for both safety metrics (arrests and crimes) are reported at the agency-level. The purpose of using the Batch Header File is to be able to link the agencies to counties for those metrics.</p>
<p>To learn more about NIBRS data, consult Jacob Kaplan’s book titled <a href="https://ucrbook.com/">Uniform Crime Reporting (UCR) Program Data: An Opinionated Guide to FBI Data</a>. For these metrics, the most important thing to know about these data is that most police agencies do not report NIBRS data prior to 2021. In 2019, only 8,500 out of approximately 18,000 police agencies in the United States (covering about 45% of the US population) reported NIBRS data. Instead, agencies primarily reported UCR data for 2020 and before. However, the FBI has moved entirely to NIBRS data starting in 2021 and no longer collects UCR data, which is why we use NIBRS data instead (<a href="https://ucrbook.com/nibrs-overview.html">source</a>).</p>
<p>We do not want to use NIBRS data for some years and UCR data for others. However, because of lack of reporting, <strong>there are a lot of missing values prior to 2021 for NIBRS data</strong>. Future updates of the safety metrics may want to include historical NIBRS data back to 2014 and should keep this in mind.</p>
<p>The Batch Header File is available as a single file covering all years on both Harvard Dataverse and ICPSR. For the 2026 metric update, we used the ICPSR version (<code>batch_header_rds_1991_2024.zip</code> from V11) which includes 2024.</p>
<p>Manually downloading these data is a three-step process:</p>
<ol type="1">
<li>Navigate to <a href="https://www.openicpsr.org/openicpsr/project/118281">Kaplan’s NIBRS data on ICPSR</a>.</li>
<li>Download <code>batch_header_rds_1991_2024.zip</code>. Complete the license/data use agreement.</li>
<li>Unzip and move <code>nibrs_batch_header_1991_2024.rds</code> to the <code>mobility-from-poverty/07_safety/data</code> directory.</li>
</ol>
</section>
<section id="load-and-clean-nibrs-batch-header-file" class="level2">
<h2 class="anchored" data-anchor-id="load-and-clean-nibrs-batch-header-file">2. Load and clean NIBRS Batch Header File</h2>
<p>This section reads in and cleans the reporting agency data contained in the Batch Header File.</p>
<section id="get-universe-of-agencies-from-the-2022-nibrs-batch-header-file" class="level3">
<h3 class="anchored" data-anchor-id="get-universe-of-agencies-from-the-2022-nibrs-batch-header-file">2.1 Get universe of agencies from the 2022 NIBRS Batch Header File</h3>
<p>Load Batch Header File</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>batch_header_file_full <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"07_safety"</span>, <span class="st">"data"</span>, <span class="st">"nibrs_batch_header_1991_2024.rds"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ICPSR V11 uses lowercase state names and abbreviations; normalize to title case</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">str_to_title</span>(state),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_abbreviation =</span> <span class="fu">str_to_upper</span>(state_abbreviation)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Filter the file to the appropriate year, select relevant necessary, and rename as necessary. We use the codebook (<code>ICPSR_38925\DS0001\38925-0001-Codebook-ICPSR</code>) to determine what each variable represents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="ot">&lt;-</span> batch_header_file_full <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2021</span>, <span class="dv">2022</span>, <span class="dv">2023</span>, <span class="dv">2024</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    ori,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    agency_indicator,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    year,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_name =</span> state,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    state_abbreviation,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    city_name,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    core_city,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_fips_1 =</span> fips_county_code_1,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_fips_2 =</span> fips_county_code_2,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_fips_3 =</span> fips_county_code_3,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_fips_4 =</span> fips_county_code_4,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_fips_5 =</span> fips_county_code_5</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Edit county FIPS codes to have three digits</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"county_fips_"</span>),</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>           <span class="sc">~</span> <span class="fu">str_pad</span>(.x, <span class="dv">3</span>, <span class="at">side =</span> <span class="st">"left"</span>, <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Change the values for core city indicator from <code>Y</code>/<code>N</code> to <code>0</code>/<code>1</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="ot">&lt;-</span> batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">core_city =</span> <span class="fu">case_when</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>      core_city <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Y"</span>, <span class="st">"y"</span>) <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="dv">1</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>      core_city <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"N"</span>, <span class="st">"n"</span>) <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="dv">0</span>),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Clean geography information on the batch header file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># See what states/territories are included</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state_name, state_abbreviation) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 54 × 3
# Groups:   state_name, state_abbreviation [54]
   state_name           state_abbreviation     n
   &lt;chr&gt;                &lt;chr&gt;              &lt;int&gt;
 1 Alabama              AL                  1942
 2 Alaska               AK                   188
 3 Arizona              AZ                   538
 4 Arkansas             AR                  1428
 5 California           CA                  3575
 6 Colorado             CO                  1189
 7 Connecticut          CT                   496
 8 Delaware             DE                   299
 9 District Of Columbia DC                    12
10 Florida              FL                  3303
# ℹ 44 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="ot">&lt;-</span> batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove US territories by name because no FIPS codes</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>state_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Guam"</span>, <span class="st">"Puerto Rico"</span>, <span class="st">"Virgin Islands"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># The NIBRS data abbreviates Nebraska as "NB" instead of its correct abbreviation "NE"</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_abbreviation =</span> <span class="fu">if_else</span>(state_abbreviation<span class="sc">==</span><span class="st">"NB"</span>, <span class="st">"NE"</span>, state_abbreviation),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Wyoming is also named "Wyoming V2" but it is unclear why</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_name =</span> <span class="fu">if_else</span>(state_name<span class="sc">==</span><span class="st">"Wyoming V2"</span>, <span class="st">"Wyoming"</span>, state_name)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The batch header file identifies state by name and abbreviation, but not state FIPS code. We manually add on state FIPS codes to the batch header file</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create crosswalk of state FIPS codes to state names/abbreviations</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>state_fips_xw <span class="ot">&lt;-</span> <span class="fu">tribble</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>state_fips, <span class="sc">~</span>state_abbreviation, <span class="sc">~</span>state_name,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"01"</span>, <span class="st">"AL"</span>, <span class="st">"Alabama"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"02"</span>, <span class="st">"AK"</span>, <span class="st">"Alaska"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"04"</span>, <span class="st">"AZ"</span>, <span class="st">"Arizona"</span>, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"05"</span>, <span class="st">"AR"</span>, <span class="st">"Arkansas"</span>,   </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"06"</span>, <span class="st">"CA"</span>, <span class="st">"California"</span>, </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"08"</span>, <span class="st">"CO"</span>, <span class="st">"Colorado"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"09"</span>, <span class="st">"CT"</span>, <span class="st">"Connecticut"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"10"</span>, <span class="st">"DE"</span>, <span class="st">"Delaware"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"11"</span>, <span class="st">"DC"</span>, <span class="st">"District of Columbia"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"12"</span>, <span class="st">"FL"</span>, <span class="st">"Florida"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"13"</span>, <span class="st">"GA"</span>, <span class="st">"Georgia"</span>,    </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"15"</span>, <span class="st">"HI"</span>, <span class="st">"Hawaii"</span>,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"16"</span>, <span class="st">"ID"</span>, <span class="st">"Idaho"</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"17"</span>, <span class="st">"IL"</span>, <span class="st">"Illinois"</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"18"</span>, <span class="st">"IN"</span>, <span class="st">"Indiana"</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"19"</span>, <span class="st">"IA"</span>, <span class="st">"Iowa"</span>,   </span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"20"</span>, <span class="st">"KS"</span>, <span class="st">"Kansas"</span>, </span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"21"</span>, <span class="st">"KY"</span>, <span class="st">"Kentucky"</span>,   </span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"22"</span>, <span class="st">"LA"</span>, <span class="st">"Louisiana"</span>,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"23"</span>, <span class="st">"ME"</span>, <span class="st">"Maine"</span>,</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"24"</span>, <span class="st">"MD"</span>, <span class="st">"Maryland"</span>,</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"25"</span>, <span class="st">"MA"</span>, <span class="st">"Massachusetts"</span>,</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"26"</span>, <span class="st">"MI"</span>, <span class="st">"Michigan"</span>,   </span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"27"</span>, <span class="st">"MN"</span>, <span class="st">"Minnesota"</span>,  </span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"28"</span>, <span class="st">"MS"</span>, <span class="st">"Mississippi"</span>,    </span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"29"</span>, <span class="st">"MO"</span>, <span class="st">"Missouri"</span>,   </span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"30"</span>, <span class="st">"MT"</span>, <span class="st">"Montana"</span>,    </span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>  <span class="st">"31"</span>, <span class="st">"NE"</span>, <span class="st">"Nebraska"</span>,   </span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"32"</span>, <span class="st">"NV"</span>, <span class="st">"Nevada"</span>, </span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>  <span class="st">"33"</span>, <span class="st">"NH"</span>, <span class="st">"New Hampshire"</span>,  </span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"34"</span>, <span class="st">"NJ"</span>, <span class="st">"New Jersey"</span>, </span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>  <span class="st">"35"</span>, <span class="st">"NM"</span>, <span class="st">"New Mexico"</span>, </span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>  <span class="st">"36"</span>, <span class="st">"NY"</span>, <span class="st">"New York"</span>,   </span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>  <span class="st">"37"</span>, <span class="st">"NC"</span>, <span class="st">"North Carolina"</span>,</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>  <span class="st">"38"</span>, <span class="st">"ND"</span>, <span class="st">"North Dakota"</span>,   </span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>  <span class="st">"39"</span>, <span class="st">"OH"</span>, <span class="st">"Ohio"</span>,   </span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>  <span class="st">"40"</span>, <span class="st">"OK"</span>, <span class="st">"Oklahoma"</span>,   </span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>  <span class="st">"41"</span>, <span class="st">"OR"</span>, <span class="st">"Oregon"</span>, </span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>  <span class="st">"42"</span>, <span class="st">"PA"</span>, <span class="st">"Pennsylvania"</span>,   </span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a>  <span class="st">"44"</span>, <span class="st">"RI"</span>, <span class="st">"Rhode Island"</span>,   </span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>  <span class="st">"45"</span>, <span class="st">"SC"</span>, <span class="st">"South Carolina"</span>, </span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>  <span class="st">"46"</span>, <span class="st">"SD"</span>, <span class="st">"South Dakota"</span>,</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>  <span class="st">"47"</span>, <span class="st">"TN"</span>, <span class="st">"Tennessee"</span>,</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a>  <span class="st">"48"</span>, <span class="st">"TX"</span>, <span class="st">"Texas"</span>,  </span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a>  <span class="st">"49"</span>, <span class="st">"UT"</span>, <span class="st">"Utah"</span>,   </span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a>  <span class="st">"50"</span>, <span class="st">"VT"</span>, <span class="st">"Vermont"</span>,    </span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a>  <span class="st">"51"</span>, <span class="st">"VA"</span>, <span class="st">"Virginia"</span>,   </span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a>  <span class="st">"53"</span>, <span class="st">"WA"</span>, <span class="st">"Washington"</span>, </span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a>  <span class="st">"54"</span>, <span class="st">"WV"</span>, <span class="st">"West Virginia"</span>,  </span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a>  <span class="st">"55"</span>, <span class="st">"WI"</span>, <span class="st">"Wisconsin"</span>,  </span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>  <span class="st">"56"</span>, <span class="st">"WY"</span>, <span class="st">"Wyoming"</span></span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Join state FIPS codes onto the batch header file</span></span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="ot">&lt;-</span> batch_header_file <span class="sc">|&gt;</span> </span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a>  tidylog<span class="sc">::</span><span class="fu">left_join</span>(</span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> state_fips_xw, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"state_name"</span>, <span class="st">"state_abbreviation"</span>)</span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-62"><a href="#cb8-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-63"><a href="#cb8-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove crosswalk</span></span>
<span id="cb8-64"><a href="#cb8-64" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(state_fips_xw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exclude-state-police-and-other-state-agencies" class="level3">
<h3 class="anchored" data-anchor-id="exclude-state-police-and-other-state-agencies">2.3 Exclude state police and other state agencies</h3>
<p>Check distribution of agency types. There are 7 types of agencies. Note that I’m not sure what an agency indicator of “5” represents, and I can’t find any information about it in the <a href="https://ucrbook.com/">available documentation</a>. In data year 2022, a value of 5 represented “special agencies” (last year’s values shown below), so it could be an error in the pre-processing of this data.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Value</th>
<th style="text-align: left;">Label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: left;">Covered by another agency</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: left;">City</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: left;">County</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: left;">University or college</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: left;">State Police</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: left;">Special Agency</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: left;">Other state agencies</td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td style="text-align: left;">Tribal agencies</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: left;">Federal agencies</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(agency_indicator) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> n<span class="sc">/</span><span class="fu">nrow</span>(batch_header_file))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       agency_indicator     n    percent
1                     5  4142 0.04736042
2                  city 55861 0.63872532
3                county 12439 0.14222990
4        other agencies  5202 0.05948066
5          state police  4667 0.05336337
6                tribal   887 0.01014213
7 university or college  4259 0.04869822</code></pre>
</div>
</div>
<p>State agencies cover multiple counties, so we remove these agencies for simplicity. Note that in data year 2022, we also removed “other state agencies” but that isn’t a category in data year 2023. They could be included in the new “other agencies” category, but I’m not sure how to be certain, so leaving this category for now.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="ot">&lt;-</span> batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>agency_indicator <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"state police"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>376 observations have a missing county FIPS value in 2023.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset data to examine further</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>bhf_missing_county <span class="ot">&lt;-</span> batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(county_fips_1))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>bhf_missing_county <span class="sc">|&gt;</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year   n
1 2021 367
2 2022 370
3 2023 376
4 2024 384</code></pre>
</div>
</div>
</section>
</section>
<section id="join-county-fips-codes-onto-nibrs-agencies-that-are-missing-county-using-law-enforcement-agency-identifiers-crosswalk" class="level2">
<h2 class="anchored" data-anchor-id="join-county-fips-codes-onto-nibrs-agencies-that-are-missing-county-using-law-enforcement-agency-identifiers-crosswalk">3. Join county FIPS codes onto NIBRS agencies that are missing county using Law Enforcement Agency Identifiers Crosswalk</h2>
<p>The goal of this section is to match a county FIPS code onto every agency in the 2022 NIBRS Batch Header File. The Batch Header File already includes a county FIPS code for each county associated with a place, but we just showed that 260 agencies still do not have a county associated with them. We attempt to get county information for these agencies using the Law Enforcement Agency Identifiers Crosswalk (LEAIC).</p>
<section id="background-on-leaic-and-manual-download" class="level3">
<h3 class="anchored" data-anchor-id="background-on-leaic-and-manual-download">3.1 Background on LEAIC and manual download</h3>
<p>To address the agencies that are missing county information, we use the 2012 Law Enforcement Agency Identifiers Crosswalk (LEAIC)</p>
<p>The LEAIC facilitates linking reported crime data with socio-economic data. The LEAIC file is available for download from the National Archive of Criminal Justice Data (NACJD) available through ICPSR at the following link:</p>
<ul>
<li><a href="https://www.icpsr.umich.edu/web/NACJD/studies/35158">LEAIC</a></li>
</ul>
<p>Note that 2012 is the most recent year for which this crosswalk is available. This may present issues in harmonizing data across years, because some counties have changed since 2012. Future updates should check if a more recent crosswalk is available yet.</p>
<p>Accessing these data requires an ICPSR account. Manually downloading these data is a five-step process, but you will only need to do each of these steps once for the creation of this metric:</p>
<ol type="1">
<li>Create an ICPSR account <a href="https://www.icpsr.umich.edu/cgi-bin/newacct">here</a>.</li>
<li>Navigate to the National Archive of Criminal Justice Data (NACJD) landing page for the LEAIC <a href="https://www.icpsr.umich.edu/web/NACJD/studies/35158">here</a>).</li>
<li>Select <code>Download</code>
<ul>
<li>Select <code>Delimited</code></li>
<li>Select <code>Agree</code> on the <code>Terms of Use</code></li>
</ul></li>
<li>Sign into your ICPSR account</li>
<li>This will download a zip file titled <code>ICPSR_35158-V2</code>. Unzip the file and navigate to <code>ICPSR_35158\DS0001\35158-0001-Data.tsv</code>. Move this file to the <code>mobility-from-poverty\07_safety\data</code> directory after you have cloned the repository for this project from GitHub.</li>
</ol>
</section>
<section id="load-and-clean-leaic" class="level3">
<h3 class="anchored" data-anchor-id="load-and-clean-leaic">3.2 Load and clean LEAIC</h3>
<p>After downloading the LEAIC, read it in. This file has a county FIPS linked to every reporting agency.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in crosswalk</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>leaic <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"07_safety"</span>, <span class="st">"data"</span>, <span class="st">"35158-0001-Data.tsv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>324 of the 376 agencies with missing county information from the Batch Header File are in the LEAIC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check how many agencies with missing county are in LEAIC</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(bhf_missing_county<span class="sc">$</span>ori <span class="sc">%in%</span> leaic<span class="sc">$</span>ORI9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1298</code></pre>
</div>
</div>
<p>Limit file to necessary variables and rename. We use the codebook (<code>ICPSR_35158\DS0001\35158-0001-Codebook</code>) to determine what each variable represents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>leaic <span class="ot">&lt;-</span> leaic <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ori =</span> ORI9,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># state = FIPS_ST,</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_fips =</span> FIPS_COUNTY</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove agencies with invalid ORI</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ori <span class="sc">!=</span> <span class="st">"-1"</span>) <span class="co"># Not in UCR/NCIC </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="join-leaic-onto-nibrs-data-with-missing-counties-by-agency-identifier" class="level3">
<h3 class="anchored" data-anchor-id="join-leaic-onto-nibrs-data-with-missing-counties-by-agency-identifier">3.3 Join LEAIC onto NIBRS data with missing counties by agency identifier</h3>
<p>Join the LEAIC to the 2023 NIBRS Batch Header File by agency. 52 agencies still have no county after using the county information from LEAIC. Most of these observations are tribal or other agencies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>bhf_missing_county <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> bhf_missing_county <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"county_fips"</span>)),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> leaic,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"ori"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>bhf_missing_county <span class="sc">|&gt;</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(county_fips)) <span class="sc">|&gt;</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(agency_indicator)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  agency_indicator   n
1                5   6
2   other agencies  80
3           tribal 113</code></pre>
</div>
</div>
</section>
<section id="use-leaic-to-create-final-agency-county-data" class="level3">
<h3 class="anchored" data-anchor-id="use-leaic-to-create-final-agency-county-data">3.4 Use LEAIC to create final agency-county data</h3>
<p>Replace county information in NIBRS data for observations that initially had a missing county value of with the updated county information from LEAIC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="ot">&lt;-</span> batch_header_file <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Drop the 376 NIBRS agencies with a missing county value</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(county_fips_1)) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Append those 376 agencies back onto main data with the county info gleaned from LEAIC</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(bhf_missing_county)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>batch_header_file <span class="ot">&lt;-</span> batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Drop the 54 NIBRS agencies that had no county info in LEAIC</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter(!is.na(county)) %&gt;%</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Assign county fips from LEAIC to the NIBRS county fips variable</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">county_fips_1 =</span> <span class="fu">if_else</span>(</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">is.na</span>(county_fips_1) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(county_fips),</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    county_fips,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    county_fips_1</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>county_fips)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove obsolete files</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co">#rm(leaic, bhf_missing_county)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="construct-county-level-population-and-demographics-using-acs" class="level2">
<h2 class="anchored" data-anchor-id="construct-county-level-population-and-demographics-using-acs">4. Construct county-level population and demographics using ACS</h2>
<p>Recall that this file serves as a precursor file to the files that create both of our metrics, which are:</p>
<ul>
<li>Reported violent crimes per 100,000 people and reported property crimes per 100,000 people</li>
<li>Juvenile arrests per 100,000 juveniles</li>
</ul>
<p>Additionally, for the juvenile arrests metric, we are interested in subgroups by age, race, and sex. To calculate these rates (both total and by subgroup), we need total population and demographic information for our denominators. We pull total population and demographic data from the 5-year ACS files for each year 2021-2022.</p>
<p>This section relies on the <code>tidycensus</code> package, which requires a Census API key. You can acquire a key <a href="https://api.census.gov/data/key_signup.html">here</a> and learn more about installing your key <a href="https://walker-data.com/tidycensus/reference/census_api_key.html">here</a>. Replace <code>[YOUR-KEY-HERE]</code> in the code below with your Census API key (leave the quotation marks).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set Census API once</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tidycensus::census_api_key("[YOUR-KEY-HERE]", install=TRUE, overwrite = TRUE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="check-acs-variable-names-and-identify-those-we-need" class="level3">
<h3 class="anchored" data-anchor-id="check-acs-variable-names-and-identify-those-we-need">4.1 Check ACS variable names and identify those we need</h3>
<p>Load ACS variables for our first and last years. Manually explore each file and spot check several observations. The naming conventions of ACS variables do not seem to change during our time period. Note that if they did we would need to split up the code that reads in the years below. Note that future updates of the safety metrics may want to pull data back to 2014, in which case the first year should be changed below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check ACS variables for the first and last years to see if they change over time</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>variables_fy <span class="ot">&lt;-</span> tidycensus<span class="sc">::</span><span class="fu">load_variables</span>(<span class="dv">2021</span>, <span class="st">"acs5"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>variables_ly <span class="ot">&lt;-</span> tidycensus<span class="sc">::</span><span class="fu">load_variables</span>(<span class="dv">2024</span>, <span class="st">"acs5"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>test_fy <span class="ot">&lt;-</span> variables_fy <span class="sc">|&gt;</span> <span class="fu">filter</span>(name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"B01003_001"</span>, <span class="st">"B01001_005"</span>, <span class="st">"B01001_006"</span>, <span class="st">"B01001_029"</span>, <span class="st">"B01001_030"</span>, <span class="st">"B01001A_005"</span>, <span class="st">"B01001B_005"</span>, <span class="st">"B01001C_005"</span>, <span class="st">"B01001D_005"</span>, <span class="st">"B01001E_005"</span>))</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(test_fy)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>test_ly <span class="ot">&lt;-</span> variables_ly <span class="sc">|&gt;</span> <span class="fu">filter</span>(name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"B01003_001"</span>, <span class="st">"B01001_005"</span>, <span class="st">"B01001_006"</span>, <span class="st">"B01001_029"</span>, <span class="st">"B01001_030"</span>, <span class="st">"B01001A_005"</span>, <span class="st">"B01001B_005"</span>, <span class="st">"B01001C_005"</span>, <span class="st">"B01001D_005"</span>, <span class="st">"B01001E_005"</span>))</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(test_ly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="create-vectors-for-years-and-variables-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="create-vectors-for-years-and-variables-of-interest">4.2 Create vectors for years and variables of interest</h3>
<p>Note that the <code>two or more race</code> variable is not appearing and may not be available at the county level. Note that if additional subgroups for either safety metric are desired in future updates, the variables pulled here may need updated. Note that future updates of the safety metrics may want to pull data back to 2014, in which case the list of years should be changed below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a list of all our years</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>years <span class="ot">&lt;-</span> <span class="fu">lst</span>(<span class="dv">2021</span>, <span class="dv">2022</span>, <span class="dv">2023</span>, <span class="dv">2024</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector for our ACS variables of interest</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>my_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_people =</span> <span class="st">"B01003_001"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014 =</span> <span class="st">"B01001_005"</span>, </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517 =</span> <span class="st">"B01001_006"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014 =</span> <span class="st">"B01001_029"</span>, </span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517 =</span> <span class="st">"B01001_030"</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_white =</span> <span class="st">"B01001A_005"</span>, </span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_black =</span> <span class="st">"B01001B_005"</span>,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_aian =</span> <span class="st">"B01001C_005"</span>, </span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_asin =</span> <span class="st">"B01001D_005"</span>,</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_nhpi =</span> <span class="st">"B01001E_005"</span>, </span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_othr =</span> <span class="st">"B01001F_005"</span>,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_twom =</span> <span class="st">"B01001G_005"</span>,</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_white_nh =</span> <span class="st">"B01001H_005"</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1014_hispanic =</span> <span class="st">"B01001I_005"</span>,</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_white =</span> <span class="st">"B01001A_006"</span>, </span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_black =</span> <span class="st">"B01001B_006"</span>,</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_aian =</span> <span class="st">"B01001C_006"</span>, </span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_asin =</span> <span class="st">"B01001D_006"</span>,</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_nhpi =</span> <span class="st">"B01001E_006"</span>, </span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_othr =</span> <span class="st">"B01001F_006"</span>,</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_twom =</span> <span class="st">"B01001G_006"</span>,</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_white_nh =</span> <span class="st">"B01001H_006"</span>, </span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_m_1517_hispanic =</span> <span class="st">"B01001I_006"</span>,</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_white =</span> <span class="st">"B01001A_020"</span>, </span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_black =</span> <span class="st">"B01001B_020"</span>,</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_aian =</span> <span class="st">"B01001C_020"</span>, </span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_asin =</span> <span class="st">"B01001D_020"</span>,</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_nhpi =</span> <span class="st">"B01001E_020"</span>, </span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_othr =</span> <span class="st">"B01001F_020"</span>,</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_twom =</span> <span class="st">"B01001G_020"</span>,</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_white_nh =</span> <span class="st">"B01001H_020"</span>,</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1014_hispanic =</span> <span class="st">"B01001I_020"</span>,</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_white =</span> <span class="st">"B01001A_021"</span>, </span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_black =</span> <span class="st">"B01001B_021"</span>,</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_aian =</span> <span class="st">"B01001C_021"</span>, </span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_asin =</span> <span class="st">"B01001D_021"</span>,</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_nhpi =</span> <span class="st">"B01001E_021"</span>,</span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_othr =</span> <span class="st">"B01001F_021"</span>,</span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_twom =</span> <span class="st">"B01001G_021"</span>,</span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_white_nh =</span> <span class="st">"B01001H_021"</span>, </span>
<span id="cb23-46"><a href="#cb23-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">age_f_1517_hispanic =</span> <span class="st">"B01001I_021"</span></span>
<span id="cb23-47"><a href="#cb23-47" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="pull-5-year-acs-data-for-all-years-2021-2022-at-the-county-level" class="level3">
<h3 class="anchored" data-anchor-id="pull-5-year-acs-data-for-all-years-2021-2022-at-the-county-level">4.3 Pull 5-year ACS data for all years 2021-2022 at the county level</h3>
<p>Pull 5-year ACS data at the county level for each year</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>county_demo_full <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  years,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> tidycensus<span class="sc">::</span><span class="fu">get_acs</span>(</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">variables =</span> my_vars,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> .x,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">output =</span> <span class="st">"wide"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">geometry =</span> <span class="cn">FALSE</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a year variable for each year</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">.id =</span> <span class="st">"year"</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove Puerto Rico from ACS data</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>county_demo <span class="ot">&lt;-</span> county_demo_full <span class="sc">|&gt;</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state_fips =</span> <span class="fu">substr</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">county_fips =</span> <span class="fu">substr</span>(GEOID, <span class="dv">3</span>, <span class="dv">5</span>)) <span class="sc">|&gt;</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state_fips <span class="sc">!=</span> <span class="st">"72"</span>)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove obsolete files</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(variables_fy, variables_ly, years, my_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="clean-acs-data" class="level3">
<h3 class="anchored" data-anchor-id="clean-acs-data">4.4 Clean ACS data</h3>
<p>Clean variable names and drop margins of error</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>county_demo <span class="ot">&lt;-</span> county_demo <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(<span class="sc">~</span> <span class="fu">sub</span>(<span class="st">"E$"</span>, <span class="st">""</span>, .x), <span class="fu">everything</span>()) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="fu">ends_with</span>(<span class="st">"M"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="a-construct-subgroups-for-raceethnicity-sex-and-age-subgroups" class="level4">
<h4 class="anchored" data-anchor-id="a-construct-subgroups-for-raceethnicity-sex-and-age-subgroups">4.4a Construct subgroups for race/ethnicity, sex, and age subgroups</h4>
<p>For the rate of juvenile arrests per 100,000 juveniles metric, we want subgroups by race, sex, and age subgroups. These are subgroups of all observations ages 10-17, so the sum of each subgroup should equal the total number of observations ages 10-17.</p>
<ul>
<li>Race: white, Black, Hispanic, Asian/other</li>
<li>Sex: male, female</li>
<li>Age: ages 10-14, ages 15-17</li>
</ul>
<p>Note that there is a Non-Hispanic white category, but not a Non-Hispanic category for other races (Black, Asian, etc.). This means that the categories will have a small but non-zero overlap. The race/ethnicity categories actually used in the <code>juvenile-arrests</code> metric are white, Black, Asian/other, and Hispanic. These are not mutually exclusive (e.g., someone could be counted as both Black and Hispanic), which matches the population denominators created here (this is because ACS doesn’t have counts of non-Hispanic Black or other non-Hispanic races other than white).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the total for ages 10-17 and the race, sex, and age subgroups</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>county_demo <span class="ot">&lt;-</span> county_demo <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Total age 10-17</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017 =</span> age_m_1014 <span class="sc">+</span> age_m_1517 <span class="sc">+</span> age_f_1014 <span class="sc">+</span> age_f_1517,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Race subgroups</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_white =</span> age_m_1014_white <span class="sc">+</span> age_m_1517_white <span class="sc">+</span> age_f_1014_white <span class="sc">+</span> age_f_1517_white,</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_black =</span> age_m_1014_black <span class="sc">+</span> age_m_1517_black <span class="sc">+</span> age_f_1014_black <span class="sc">+</span> age_f_1517_black,</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_aian =</span> age_m_1014_aian <span class="sc">+</span> age_m_1517_aian <span class="sc">+</span> age_f_1014_aian <span class="sc">+</span> age_f_1517_aian,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_asin =</span> age_m_1014_asin <span class="sc">+</span> age_m_1517_asin <span class="sc">+</span> age_f_1014_asin <span class="sc">+</span> age_f_1517_asin,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_nhpi =</span> age_m_1014_nhpi <span class="sc">+</span> age_m_1517_nhpi <span class="sc">+</span> age_f_1014_nhpi <span class="sc">+</span> age_f_1517_nhpi,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_othr =</span> age_m_1014_othr <span class="sc">+</span> age_m_1517_othr <span class="sc">+</span> age_f_1014_othr <span class="sc">+</span> age_f_1517_othr,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># age_1017_twom = age_m_1014_twom + age_m_1517_twom + age_f_1014_twom + age_f_1517_twom,</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_hispanic =</span> age_m_1014_hispanic <span class="sc">+</span> age_m_1517_hispanic <span class="sc">+</span> age_f_1014_hispanic <span class="sc">+</span> age_f_1517_hispanic,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_white_nh =</span> age_m_1014_white_nh <span class="sc">+</span> age_m_1517_white_nh <span class="sc">+</span> age_f_1014_white_nh <span class="sc">+</span> age_f_1517_white_nh,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sex subgroups</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex_1017_m =</span> age_m_1014 <span class="sc">+</span> age_m_1517,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex_1017_f =</span> age_f_1014 <span class="sc">+</span> age_f_1517,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Age subgroups</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1014_all =</span> age_m_1014 <span class="sc">+</span> age_f_1014,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1517_all =</span> age_m_1517 <span class="sc">+</span> age_f_1517</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Edit race variables  </span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>county_demo <span class="ot">&lt;-</span> county_demo <span class="sc">|&gt;</span>  </span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Manually create "two or more" race variable</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_twom =</span> age_1017 <span class="sc">-</span> age_1017_white <span class="sc">-</span> age_1017_black <span class="sc">-</span> </span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>      age_1017_aian <span class="sc">-</span> age_1017_asin <span class="sc">-</span> age_1017_nhpi <span class="sc">-</span> age_1017_othr,</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Combine all asian races, other races, and two or more races</span></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_1017_asian_other =</span> age_1017_aian <span class="sc">+</span> age_1017_asin <span class="sc">+</span> age_1017_nhpi <span class="sc">+</span></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>      age_1017_othr <span class="sc">+</span> age_1017_twom</span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Limit ACS data to relevant variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Limit to relevant variables</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>county_demo <span class="ot">&lt;-</span> county_demo <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, GEOID, state_fips, county_fips, total_people, <span class="fu">starts_with</span>(<span class="st">"age_1017"</span>), <span class="fu">starts_with</span>(<span class="st">"sex_1017"</span>), <span class="fu">ends_with</span>(<span class="st">"_all"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Test that construction of each subgroup worked as expected</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowSums</span>(<span class="fu">select</span>(county_demo, <span class="fu">matches</span>(<span class="st">"age_1017_asian_other|age_1017_white$|age_1017_black"</span>)), <span class="at">na.rm =</span> T) <span class="sc">==</span> county_demo<span class="sc">$</span>age_1017</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowSums</span>(<span class="fu">select</span>(county_demo, <span class="fu">matches</span>(<span class="st">"age_1517_all|age_1014_all"</span>)), <span class="at">na.rm =</span> T) <span class="sc">==</span> county_demo<span class="sc">$</span>age_1017</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowSums</span>(<span class="fu">select</span>(county_demo, <span class="fu">matches</span>(<span class="st">"sex_1017_m|sex_1017_f"</span>)), <span class="at">na.rm =</span> T) <span class="sc">==</span> county_demo<span class="sc">$</span>age_1017</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="join-batch-header-file-onto-acs-county-demographics-by-county" class="level2">
<h2 class="anchored" data-anchor-id="join-batch-header-file-onto-acs-county-demographics-by-county">5. Join Batch Header File onto ACS county demographics by county</h2>
<section id="reshape-bhf-to-be-long-by-agency-and-county" class="level3">
<h3 class="anchored" data-anchor-id="reshape-bhf-to-be-long-by-agency-and-county">5.1 Reshape BHF to be long by agency and county</h3>
<p>The NIBRS batch header file is currently long by <code>ori</code> (agency), such that there is one observation for each agency. These agencies have variables that contain county FIPS codes for each of the counties that agency serves.</p>
<p>692 agencies cover 2 counties, 69 agencies cover 3 counties, 10 agencies cover 4 counties, 0 agencies cover 5 counties</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(batch_header_file<span class="sc">$</span>county_fips_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2763</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(batch_header_file<span class="sc">$</span>county_fips_3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 262</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(batch_header_file<span class="sc">$</span>county_fips_4))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(batch_header_file<span class="sc">$</span>county_fips_5))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>We reshape the data to be long by <code>ori</code> and <code>county</code> such that each observation represents each unique <code>ori</code> and <code>county</code> pair.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape NIBRS data to be long by agency AND county</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>batch_header_file_long <span class="ot">&lt;-</span> batch_header_file <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"county_fips_"</span>),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"county_fips"</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Remove observations that are not relevant to more that one county</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(county_fips) <span class="sc">|&gt;</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(name))</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="co">#mutate(across(starts_with("fips"), ~str_pad(., 3, pad = "0"))) |&gt;</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">#select(c(ori, agency_indicator, core_city, starts_with("state"), starts_with("fips"))) |&gt;</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#pivot_longer(-c(ori, core_city), values_to = "county")</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co">#batch_header_file &lt;- batch_header_file |&gt;</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#filter(!is.na(county_fips))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="join-the-nibrs-data-batch-header-file-onto-the-acs-county-population-and-demographics" class="level3">
<h3 class="anchored" data-anchor-id="join-the-nibrs-data-batch-header-file-onto-the-acs-county-population-and-demographics">5.2 Join the NIBRS data (Batch Header File) onto the ACS county population and demographics</h3>
<p>Join agency/county pairs onto the ACS county/year-level population and demographics</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create GEOID</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>batch_header_file_long <span class="ot">&lt;-</span> batch_header_file_long <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">GEOID =</span> <span class="fu">str_c</span>(state_fips, county_fips))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Join data</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>joined_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> county_demo <span class="sc">|&gt;</span> </span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(year, GEOID, total_people) <span class="sc">|&gt;</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">as.numeric</span>(year)),</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> batch_header_file_long,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"GEOID"</span>, <span class="st">"year"</span>)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="a-investigate-unmatched-observations" class="level4">
<h4 class="anchored" data-anchor-id="a-investigate-unmatched-observations">5.2a Investigate unmatched observations</h4>
<section id="a.i-observations-in-pooled-acs-data-but-not-in-the-2023-batch-header-file" class="level5">
<h5 class="anchored" data-anchor-id="a.i-observations-in-pooled-acs-data-but-not-in-the-2023-batch-header-file">5.2a.i Observations in pooled ACS data but not in the 2023 Batch Header File</h5>
<p>7 observations are in the pooled ACS data but not in the 2023 Batch Header File.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> county_demo,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> batch_header_file_long, </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"GEOID"</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check which states the unmatched observations come from</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>test <span class="sc">|&gt;</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">substr</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state) <span class="sc">|&gt;</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
# Groups:   state [3]
  state     n
  &lt;chr&gt; &lt;int&gt;
1 02       24
2 11        4
3 15        4</code></pre>
</div>
</div>
<p>6 of the unmatched observations that are in the ACS but not the Batch Header File are from Alaska, and 1 is from Hawaii. Note that Connecticut adopted the state’s nine Councils of Government as the county-equivalent geographic unit, and this change is reflected in ACS data products for the first time in 2022 (<a href="https://www.census.gov/programs-surveys/acs/technical-documentation/table-and-geography-changes/2022/geography-changes.html">source</a>). This update to the safety metric ignores this change for now, but future updates may be interested in harmonizing Connecticut counties across years. <a href="https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.html">These relationship files</a> may (or may not) be helpful in accomplishing that task.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>test <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">substr</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"09"</span>) <span class="sc">|&gt;</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state, year) <span class="sc">|&gt;</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 3
# Groups:   state, year [0]
# ℹ 3 variables: state &lt;chr&gt;, year &lt;chr&gt;, n &lt;int&gt;</code></pre>
</div>
</div>
<p>Note that Kalawao County, HI is the smallest county in the 50 states by land area and the second-smallest county by population. Because of the small population, it does not have the same functions as other Hawaii counties and is instead a judicial district of Maui County. It is entirely plausible that this county is missing from the Batch Header File because it does not have any police agencies, or if it does, the agencies have not reported NIBRS data. We ignore these observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>test <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">substr</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"15"</span>) <span class="sc">|&gt;</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GEOID, year) <span class="sc">|&gt;</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(total_people)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
# Groups:   GEOID, year [4]
  GEOID year  total_people     n
  &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt;
1 15005 2021            48     1
2 15005 2022            50     1
3 15005 2023            43     1
4 15005 2024            67     1</code></pre>
</div>
</div>
<p>The remaining unmatched observations that are in the ACS but not the Batch Header File are from Alaska. There are 6 observations for 2021 and 6 observations for 2022. <a href="https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2010.html#list-tab-957819518">This documentation</a> explains the following changes to counties in Alaska that account for 4/12 of these unmatched observations.</p>
<ul>
<li>Chugach Census Area (02063) was created from part of former Valdez-Cordova Census Area (02261) effective January 02, 2019</li>
<li>Copper River Census Area (02066) was created from part of former Valdez-Cordova Census Area (02261) effective January 02, 2019</li>
</ul>
<p>Note that future updates may want to account for the change to these counties.</p>
<p>The other 8/12 unmatched observations are from the following counties: Denali Borough (02068), Lake and Peninsula Borough (02164), Southeast Fairbanks Census Area (02240), and the City and Borough of Yakutat (02282). Note that all four of these counties have very small populations. It is entirely plausible that these counties are missing from the Batch Header File because they do not have any police agencies, or if they do, the agencies have not reported NIBRS data. We ignore these observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>test <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">state =</span> <span class="fu">substr</span>(GEOID, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">"02"</span>) <span class="sc">|&gt;</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GEOID, year) <span class="sc">|&gt;</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(total_people)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 4
# Groups:   GEOID, year [24]
   GEOID year  total_people     n
   &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt;
 1 02063 2021          7015     1
 2 02063 2022          7000     1
 3 02063 2023          6964     1
 4 02063 2024          6862     1
 5 02066 2021          2635     1
 6 02066 2022          2614     1
 7 02066 2023          2626     1
 8 02066 2024          2626     1
 9 02068 2021          2187     1
10 02068 2022          2101     1
# ℹ 14 more rows</code></pre>
</div>
</div>
</section>
<section id="a.ii-observations-in-the-2022-batch-header-file-but-not-in-the-pooled-acs-data" class="level5">
<h5 class="anchored" data-anchor-id="a.ii-observations-in-the-2022-batch-header-file-but-not-in-the-pooled-acs-data">5.2a.ii Observations in the 2022 Batch Header File but not in the pooled ACS data</h5>
<p>9 observations are in the 2022 Batch Header File but not the pooled ACS data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(test)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> batch_header_file_long,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> county_demo,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"GEOID"</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check which counties the unmatched observations come from</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>test <span class="sc">|&gt;</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GEOID) <span class="sc">|&gt;</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
# Groups:   GEOID [3]
  GEOID     n
  &lt;chr&gt; &lt;int&gt;
1 02261    12
2 46113     8
3 &lt;NA&gt;     12</code></pre>
</div>
</div>
<p>3/5 of the unmatched observations that are in the 2022 Batch Header File but not the pooled ACS data are from Valdez-Cordova Census Area, Alaska (02261). <a href="https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2010.html#list-tab-957819518">This documentation</a> explains that Valdez-Cordova Census Area was split into Chugach Census Area, Alaska (02063) and Copper River Census Area (02066) effective January 02, 2019. It appears that at least some of the 2022 Batch Header File agencies have not accounted for this change. Note that future updates may want to account for the change to this county, but we ignore these observations for now.</p>
<p>2/5 of the unmatched observations that are in the 2022 Batch Header File but not the pooled ACS data are from Shannon County, South Dakota (46113). <a href="https://www.census.gov/programs-surveys/geography/technical-documentation/county-changes.2010.html#list-tab-957819518">This documentation</a> explains that Shannon County, SD changed its name and FIPS code to Oglala Lakota County (46102) effective May 1, 2015. We correct the 2023 Batch Header File for this change below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>batch_header_file_long <span class="ot">&lt;-</span> batch_header_file_long <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">fips_county_code =</span> <span class="fu">ifelse</span>(state_fips<span class="sc">==</span><span class="st">"46"</span> <span class="sc">&amp;</span> county_fips<span class="sc">==</span><span class="st">"113"</span>, <span class="st">"102"</span>, county_fips),</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">GEOID =</span> <span class="fu">ifelse</span>(state_fips<span class="sc">==</span><span class="st">"46"</span><span class="sc">&amp;</span> GEOID<span class="sc">==</span><span class="st">"46113"</span>, <span class="st">"46102"</span>, GEOID)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="b-re-join-the-nibrs-data-batch-header-file-onto-the-acs-county-population-and-demographics-after-harmonizing-county-changes-over-time" class="level4">
<h4 class="anchored" data-anchor-id="b-re-join-the-nibrs-data-batch-header-file-onto-the-acs-county-population-and-demographics-after-harmonizing-county-changes-over-time">5.2b Re-join the NIBRS data (Batch Header File) onto the ACS county population and demographics after harmonizing county changes over time</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join data</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>joined_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> county_demo <span class="sc">|&gt;</span> </span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(year, GEOID, total_people),</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> batch_header_file_long <span class="sc">|&gt;</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">as.character</span>(year)),</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"GEOID"</span>, <span class="st">"year"</span>)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="create-county-agency-weights" class="level2">
<h2 class="anchored" data-anchor-id="create-county-agency-weights">6. Create county-agency weights</h2>
<p>For agencies that cover multiple counties, assign weight based on county population (e.g., if Agency A has jurisdiction in both County 1 which has 10,000 people and County 2 which has 5,000 people, the weights will be 0.667 and 0.333, respectively).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make agency weights based on population of counties they cover</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>joined_data <span class="ot">&lt;-</span> joined_data <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(total_people)) <span class="sc">|&gt;</span>  </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, ori) <span class="sc">|&gt;</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">weight =</span> total_people <span class="sc">/</span> <span class="fu">sum</span>(total_people),</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">weight =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(ori), <span class="cn">NA</span>, weight)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Count number of agencies in each county.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>county_agency <span class="ot">&lt;-</span> joined_data <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GEOID, year) <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_agencies =</span> <span class="fu">n_distinct</span>(ori),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_wt =</span> <span class="fu">sum</span>(weight),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_core_city =</span> <span class="fu">sum</span>(core_city<span class="sc">==</span><span class="dv">1</span>),</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">core_city =</span> <span class="fu">max</span>(core_city),</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">#n_agen_city = sum(agency_type==1),</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">#n_agen_cnty = sum(agency_type==2),</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">#n_agen_univ = sum(agency_type==3),</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">#n_agen_spcl = sum(agency_type==5),</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>   <span class="co"># n_agen_trbl = sum(agency_type==7)</span></span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="write-out-data" class="level2">
<h2 class="anchored" data-anchor-id="write-out-data">7. Write out data</h2>
<p>Write out county demographics only</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(county_demo, <span class="at">file =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"07_safety"</span>, <span class="st">"data"</span>, <span class="st">"all_county_demo.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Write out county demographics plus agency info</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join these data</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>county_demo_agency <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> county_demo,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> county_agency, </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"GEOID"</span>)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Write out</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(county_demo_agency, <span class="at">file =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"07_safety"</span>, <span class="st">"data"</span>, <span class="st">"all_county_demo_agency.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Write out agency-county level file with weights</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(joined_data, <span class="at">file =</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"07_safety"</span>, <span class="st">"data"</span>, <span class="st">"all_agency_county.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>