---
title: ""
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    code-fold: true
    css: 10_construct-database/www/web_report.css
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

<style>
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');
</style>

<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato" />

```{r rmarkdown-setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(knitr.kable.NA = "")

```

```{r load-packages}
library(tidyverse)
library(here)
library(assertr)
library(gt)

```



```{r add-labels}
county_pop <- read_csv(here("geographic-crosswalks", "data", "county-populations.csv")) %>%
  select(state, county, state_name, county_name) %>%
  distinct()

```

Gm note: environmental index is updated to have subgroups by race share
## Environmental


```{r}
environment <- 
  read_csv(here("06_neighborhoods", "environment", "data", "output", "environment_county_sub_all.csv"), guess_max = 5000) %>%
  mutate(
    subgroup = recode(
      subgroup,
      `High Poverty` = "High Poverty Tracts",
      `Not High Poverty` = "Not High Poverty Tracts"
    )
  ) %>%
  left_join(county_pop) %>%
  relocate(year, state, county, state_name, county_name) 

write_csv(environment, here("data", "04_environmental-exposure_poverty_longitudinal.csv")) 

env_18 <- environment %>% 
  slice_max(year) %>%
  write_csv(here("data", "04_environmental-exposure_poverty_longitudinal.csv"))

```


```{r}
SEDA <- read_csv(here("08_education", "SEDA_all_subgroups_county.csv")) %>%
  filter(subgroup_type %in% c("all", "income")) %>%
  #filter(year == 2015) %>% #GM note: not obvious why we do this 
  mutate(
    subgroup = case_when(
      subgroup == "All" ~ "All",
      subgroup == "Economically Disadvantaged" ~ "Low Income",
      subgroup == "Not Economically Disadvantaged" ~ "Not Low-Income"
    )
  ) %>%
  left_join(county_pop) %>%
  relocate(year, state, county, state_name, county_name)


SEDA_recent <- SEDA %>%
  slice_max(year) %>%
  write_csv(here("data", "04_SEDA-income_recent.csv"))

write_csv(SEDA, here("data", "04_SEDA-income_longitudinal.csv"))
```

## Poverty Exposure

```{r}
files <- c(
  here("06_neighborhoods", "poverty-exposure", "poverty-exposure_race-ethnicity_county_2018.csv"),
  here("06_neighborhoods", "poverty-exposure", "poverty-exposure_race-ethnicity_county_2021.csv")
  )

pov_exposure_race_ethnicity <- lapply(files, read_csv) %>%
  bind_rows() %>%
  left_join(county_pop) %>% 
  relocate(year, state, county, state_name, county_name) %>%
  write_csv(here("data", "04_poverty-exposure_race-ethnicity_longitudinal.csv"))


read_csv(  
  here("06_neighborhoods", "poverty-exposure", "poverty-exposure_race-ethnicity_county_2021.csv")
  ) %>%
  left_join(county_pop) %>%
  relocate(year, state, county, state_name, county_name) %>%
  write_csv(
    here("data", "04_poverty-exposure_race-ethnicity_recent.csv")

  )

```




