---
title: ""
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    css: !expr here::here("10_construct-database", "www", "web_report.css")
    toc: TRUE
    toc_float: TRUE
    editor_options: 
      chunk_output_type: console
---

<style>
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');
</style>

<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato" />

```{r rmarkdown-setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(knitr.kable.NA = "")

```

```{r load-packages}
library(tidyverse)
library(here)
library(assertr)
library(gt)

```

## Environmental 

```{r}
read_csv(here("06_neighborhoods", "environment", "enviro_poverty.csv"), guess_max = 5000) %>%
  mutate(
    subgroup = recode(
      subgroup,
      `High Poverty` = "High Poverty Tracts",
      `Not High Poverty` = "Not High Poverty Tracts"
    )
  ) %>%
  write_csv(here("data", "environmental-exposure_poverty.csv"))

```

```{r}
read_csv(here("08_education", "SEDA_all_subgroups.csv")) %>%
  filter(subgroup_type %in% c("all", "income")) %>%
  filter(year == 2015) %>%
  mutate(
    subgroup = case_when(
      subgroup == "All" ~ "All",
      subgroup == "Economically Disadvantaged" ~ "Low Income",
      subgroup == "Not Economically Disadvantaged" ~ "Not Low-Income"
    )
  ) %>%
  write_csv(here("data", "SEDA_income.csv"))

```

## Poverty Exposure

```{r}
read_csv(here("06_neighborhoods", "poverty-exposure", "poverty-exposure_race-ethnicity.csv"), guess_max = 5000) %>%
  write_csv(here("data", "poverty-exposure_race.csv"))

```




