---
title: ""
author: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    code-fold: true
    css: Output/www/web_report.css
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r rmarkdown-setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(knitr.kable.NA = "")

```

```{r load-packages}
options(scipen = 999)

library(tidyverse)
library(ggplot2)
library(tidycensus)
library(plotly)
library(reactable)
library(data.table)
library(readxl)
library(qreport)

```

#Overveiew 

This document shows summary stats of the available variables in the NW HSPC data 


## All variables

The following table shows the 15 "highest" data quality counties based on a scoring metric.The highest score is 66 (all good quality, no missing) and 9 out of the 15 highest quality counties have a perfect score.

```{r county-quality-high-all}
metrics_nw <- read_csv(here::here("Data", "hscp_data.csv"))%>% 
  select(-PCode, -`1.1 Sub_Grantee_CCE_ID`, -Lat, -Lon, -`1.2 Client_Unique_Ident`, -`1.6 Intake_Date`,
         -`1.24 Address_Before_Geocoding`, -`1.25 Apt_Before_Geocoding`, -`1.26 City_Before_Geocoding`, -`1.27 State_Before_Geocoding`,
         -`1.28 Zip_Before_Geocoding`, -GeoLevel, -Geocoded_Address, -Geocoded_Address2, -Geocoded_AddressPlusSuite, -Geocoded_Full_Address,
         -Geocoded_City, -Geocoded_Zip, -Geocoded_State, -`1.42 Level_Completion_Date`, -`1.43 Record_Complete_For_Review_Payment`)


#write_csv(metrics_quality_county, here::here("10_construct-database", "mobility-metrics-quality-county.csv"))
dataOverview(metrics_nw)


```
