project:
  type: book
  output-dir: ../docs

book:
  title: "Boosting Upward Mobility from Poverty Data Documentation"
  author: "Aaron R. Williams"
  date: last-modified
  chapters:
    - index.qmd
    - part: county-datasets.qmd
      chapters: 
        - 00_mobility-metrics_longitudinal.qmd
        - 01_mobility-metrics.qmd
        - 02_mobility-metrics_race-ethnicity.qmd
        - 03_mobility-metrics_race.qmd
        - 04_mobility-metrics_race-share.qmd
    - part: city-datasets.qmd
      chapters: 
        - 00_mobility-metrics_longitudinal.qmd
    - news.qmd
    - contact.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: source

editor_options: 
  chunk_output_type: console

execute: 
  echo: false
  warning: false
  messages: false
