project:
  type: book
  output-dir: ../docs

book:
  title: "Boosting Upward Mobility from Poverty Data Documentation"
  author: "Aaron R. Williams"
  date: last-modified
  chapters:
    - index.qmd
    - part: county-datasets.qmd
      chapters: 
        - 00_mobility-metrics_longitudinal.qmd
        - 00_mobility-metrics_recent.qmd
        - 01_mobility-metrics_race-ethnicity_longitudinal.qmd
        - 02_mobility-metrics_race_longitudinal.qmd
        - 02_poverty-exposure_race-ethnicity.qmd
        - 03_mobility-metrics_race-share_longitudinal.qmd
    - part: city-datasets.qmd
      chapters: 
        - 05_mobility-metrics_place_longitudinal.qmd
        - 05_mobility-metrics_place_recent.qmd
        - 06_mobility-metrics_place_race-ethnicity_longitudinal.qmd
        - 07_mobility-metrics_place_race_longitudinal.qmd
        - 07_poverty-exposure_city_subgroup.qmd
        - 08_mobility-metrics_place_race-share.qmd
    - news.qmd
    - contact.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    toc-depth: 0
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: source

editor_options: 
  chunk_output_type: console

execute: 
  echo: false
  warning: false
  messages: false
