project:
  type: book
  output-dir: ../docs

book:
  title: "Boosting Upward Mobility from Poverty Data Documentation"
  author: "Aaron R. Williams"
  date: "2023-03-01"
  chapters:
    - index.qmd
    - part: datasets.qmd
      chapters: 
        - 00_mobility-metrics_longitudinal.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: source

editor_options: 
  chunk_output_type: console

execute: 
  echo: false
  warning: false
  messages: false
