# City Data Sets {.unnumbered}

The mobility metrics are contained in several distinct data sets. The data sets are organized according to the principles of [tidy data](https://r4ds.had.co.nz/tidy-data.html) and each data set has a unique unit of observation. 

```{r}
dimensions <- function(data) {
  
  dims <- dim(data)
  paste0(scales::comma(dims[1]), " rows and ", dims[2], " columns")
  
}

library(tidyverse)

cities_longitudinal <- read_csv("../data/05_mobility-metrics_place_longitudinal.csv")

cities <- read_csv("../data/05_mobility-metrics_place_recent.csv")

cities_race_ethnicity  <- read_csv("../data/06_mobility-metrics_place_race-ethnicity_longitudinal.csv")

cities_race  <- read_csv("../data/07_mobility-metrics_place_race_longitudinal.csv")

cities_poverty_exposure <- read_csv("../data/07_poverty-exposure_city_subgroup.csv")

cities_race_share  <- read_csv("../data/09_place_environmental-exposure_poverty_longitudinal.csv")

cities_seda <- read_csv("../data/09_place_SEDA-income_longitudinal.csv")

```

# 05_mobility-metrics_place_longitudinal.csv

* **Unit of Observation:** One row per city per year. 
* **Dimensions:** `r dimensions(cities_longitudinal)`
* **Years:** `r unique(cities_longitudinal$year)`

This data set contains all of the city-level mobility metrics for all available years. In some cases it will contain more years of data than are available in the mobility metrics data pages. 

---

# 05_mobility-metrics_place_recent.csv

* **Unit of Observation:** One row per city. 
* **Dimensions:** `r dimensions(cities)`

This data set contains all of the city-level mobility metrics for the most recent year available for each metric. For example, if one metric is available in 2018 and another metric is available in 2021, both metrics will show up in the same row in this data set. 

---

# 06_mobility-metrics_place_race-ethnicity_longitudinal.csv

* **Unit of Observation:** One row per city per race-ethnicity group per year.
* **Dimensions:** `r dimensions(cities_race_ethnicity)`
* **Years:** `r unique(cities_race_ethnicity$year)`

This data set contains mobility metrics disaggregated by race/ethnicity group when available. 

---

# 07_mobility-metrics_place_race_longitudinal.csv

* **Unit of Observation:** One row per city per race group per year.
* **Dimensions:** `r dimensions(cities_race)`
* **Years:** `r unique(cities_race$year)`

This data set contains mobility metrics disaggregated by race group when available. 

---

# 07_poverty-exposure_city_subgroup.csv

* **Unit of Observation:** One row per city per race group per year.
* **Dimensions:** `r dimensions(cities_poverty_exposure)`
* **Years:** `r unique(cities_poverty_exposure$year)`

This data set contains special race and ethnicity tabulations for the economic inclusion mobility metric.  

---

# 09_place_environmental-exposure_poverty_longitudinal.csv

* **Unit of Observation:** One row per city per majority race group in a subgeography per year.
* **Dimensions:** `r dimensions(cities_race_share)`
* **Years:** `r unique(cities_race_share$year)`

This data set contains mobility metrics disaggregated by the majority race of the subgeographies in the city. 

---

# 09_place_SEDA-income_longitudinal.csv

* **Unit of Observation:** One row per city per majority race group in a subgeography per year.
* **Dimensions:** `r dimensions(cities_seda)`
* **Years:** `r unique(cities_seda$year)`

This data set contains mobility metrics disaggregated using special disaggregations for SEDA data. 

---

The next sections provide detailed documentation for each data set.
