---
title: "Poverty Exposure - County"
author: "Aaron R. Williams, Vincent Pancini, and Manu Alcalá Kovalski"
date: now
format:
  html:
    self-contained: true
    toc: true
    css: ../../06_neighborhoods/www/web_report.css
editor_options: 
  chunk_output_type: console
execute:
  warning: false
  message: false
---


# Poverty Exposure

This metric is the share of people who are poor in a county who live in census tracts with poverty rates over 40%. If a county's overall poverty rate is 20% but people in poverty are spread out evenly across all census tracts, the index would equal 0; if they were heavily concentrated in certain tracts, the index would approach 1.

**Process:**

1. Pull people and poverty rates for Census tracts. 
2. Create the “Other Races and Ethnicities” subgroup. 
3. Count the number of people in poverty who live in Census tracts with poverty > 40% in each county. 
4. Summarize the tract data to the county-level.
5. Divide the number from 2. by the total number of people in poverty in each Census tract. 
6. Validation
7. Data quality flags

The most recent version of this metric uses ACS 2017-2021 5-Year Data, released on [2022-12-08](https://www.census.gov/newsroom/press-kits/2022/acs-5-year.html). All numbers come from the Census API. The documentation for the Census API is available [here](https://api.census.gov/data/2021/acs/acs5/profile/variables.html). We pull all of the race/ethnicity counts for 2021 using `library(censusapi)`. **Note:** This will require a [Census API key](https://api.census.gov/data/key_signup.html). Add the key to `census_api_key-template.R` and then delete "template". It is sourced above. 

To do this we have to identify census tracts with poverty rates over 40% in each county, count the number of residents in those tracts who are poor, sum that up and divide it by the total number of poor residents in the county.