---
title: ""
author: "Vincent Pancini"
---



```{r rmarkdown-setup, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r setup}
library(urbnthemes)
library(tidyverse)
library(rvest)
library(glue)
library(fs)

set_urbn_defaults(style = "print")

```

## 1. Prepare for file download
```{r}
base_url <- "https://www.countyhealthrankings.org"
url <- paste0(base_url, "/explore-health-rankings/rankings-data-documentation")
download_urls <-
  read_html(url) %>% 
  html_elements('span.field-content') %>%  
  html_element('a') %>% 
  html_attr('href') %>%
  paste0(base_url, .)

out_state <-
  read_html(url) %>% 
  html_elements('span.field-content') %>% 
  html_text2() %>% 
  str_replace_all(' ', '-')

get_state_data_url <- function(url){
  read_html(url) %>% 
    html_elements('span.download-link') %>% 
    html_element('a') %>% 
    html_attr('href') %>% 
    str_subset('.xls') %>% 
    str_subset('2022') %>% 
    paste0(base_url, .)
}
state_data_url <- purrr::map_chr(.x = download_urls, .f = get_state_data_url)
```


## 2. Download files

Download all 51 Excel files from each state's URL
```{r}
# create a data folder for intermediate data files
intermediate_files <- here::here("04_health",
                                 "access-health-services",
                                 "data/")

if (!dir.exists(intermediate_files)) {
  
  dir.create(intermediate_files)
  
}

chr_data <- here::here("04_health",
                       "access-health-services",
                       "data",
                       out_state
)

download_data <- function(state_data_url, state_name){
  if (!file.exists(here::here(glue("04_health/access-health-services/data/{state_name}.xlsx")))) {
    
    download.file(state_data_url, 
                  destfile = here::here(glue("04_health/access-health-services/data/{state_name}.xlsx")))
    
  }
}

walk2(state_data_url, out_state, download_data)

```


## 3. Read in, clean, and append each Excel sheet
```{r}
physicians <- map_dfr(out_state,
                     ~{readxl::read_excel(path = here::here(
                       paste0('04_health/access-health-services/data/', .x, '.xlsx')),
                       sheet = 'Ranked Measure Data',
                       skip = 1
                     ) %>%
                         select(fips = 'FIPS',
                                pc_phys_ratio = 'Primary Care Physicians Ratio'
                                ) %>%
                         filter(!str_detect(fips, '000$')) %>%
                         mutate(state = str_sub(fips, 1, 2),
                                county = str_sub(fips, 3, 5)
                                )
                     }
)

physicians <- physicians %>%
  separate(col = pc_phys_ratio,
           into = c('antecedent', 'consequent'),
           remove = FALSE) %>%
  mutate(pc_phys_ratio = case_when(consequent == "1" ~ pc_phys_ratio,
                                   consequent == "0" ~ "0",
                                   is.na(pc_phys_ratio) ~ "0"),
         year = 2019
         ) %>%
  select(year, state, county, pc_phys_ratio)

```


## 4. Add data quality flags
```{r}


```


## 5. Save the data
```{r}
# Is this join necessary?

all_counties <- read_csv(here::here("geographic-crosswalks", "data", "county-populations.csv")) %>%
  tidylog::filter(year == 2020) %>%
  select(-year)

joined_data <- left_join(physicians, all_counties, by = c("state", "county"))

test <- anti_join(all_counties, physicians, by = c("state", "county"))

joined_data <- joined_data %>%
  mutate(year = 2019) %>%
  select(year, state, county, pc_phys_ratio, population) %>%
  arrange(year, state, county)

joined_data %>%
  write_csv(here::here("04_health",
                       "access-health-services",
                       "access-health-services-2019.csv"))
```

